xmisao/bestgems.org

- lib/batch/update_daily_downloads.rb
- lib/batch/update_daily_ranking.rb
- lib/batch/update_total_downloads.rb
- lib/batch/update_total_ranking.rb
- lib/database.rb
This change improves the performance of batch by 50%.
> Improvement of batch performance

- .gitignore
- bin/batch.sh
- bin/migrate
- lib/batch/update_gems_latest_columns.rb
- lib/migration/migrator.rb
- migrations/006_add_latest_columns_to_gems_table.rb
- test/batch/test_update_gems_latest_columns.rb
Ref: https://github.com/xmisao/bestgems.org/issues/32
Add latest downloads/ranking columns to gems table.
This change is denormalization. But it will resolve some performance issues.
> Add latest columns

- lib/app.rb
- lib/models/gems.rb
- test/models/test_gems.rb
- views/search.erb
Ref: https://github.com/xmisao/bestgems.org/issues/32
* Improve search page rendering performance
* Improve gem page rendering performance
> Fetch latest trend from gems table

- tools/archive.rb
`tools/archive.rb` is not working with PostgreSQL.
> Fix archive

- Rakefile
- lib/batch/update_gems_latest_columns.rb
- lib/models/ranking.rb
- lib/models/trend.rb
- test/models/test_gems.rb
- tools/archive.rb
- tools/generate_dummy_data.rb
- tools/import_scraped_data.rb
Add `format` task to execute `rufo`.
```
rake format
```
> Formatting

- Gemfile
- Gemfile.lock
- bin/batch.sh
- lib/batch/scraping_all_gems.rb
- lib/batch/update_daily_downloads.rb
- lib/batch/update_daily_ranking.rb
- lib/batch/update_daily_summary.rb
- lib/batch/update_featured_ranking.rb
- lib/batch/update_featured_score.rb
- lib/batch/update_gems.rb
- lib/batch/update_gems_latest_columns.rb
- lib/batch/update_master.rb
- lib/batch/update_statistics_daily_downloads.rb
- lib/batch/update_statistics_num_of_gems.rb
- lib/batch/update_statistics_total_downloads.rb
- lib/batch/update_total_downloads.rb
- lib/batch/update_total_ranking.rb
- lib/batch/update_trends.rb
- lib/database.rb
- lib/helper/trace.rb
- lib/models/batch_logger.rb
- lib/models/master.rb
- lib/models/rubygems_page.rb
- lib/models/web_logger.rb
- test/batch/test_scraping_all_gems.rb
Change summary.
* Remove `mechanize` due to some bugs included in `2.7.6`
* Add logging to batch scripts
* Fix some bugs of batch scripts
* Cleaning scraped_data
> Refactor batch scripts

- lib/batch/update_featured_score.rb
Display gems that score are greater than 0.
> Fix featured ranking generating

- lib/app.rb
- lib/batch/write_back_values_and_rankings.rb
- lib/models/ranking.rb
- test/batch/test_update_daily_summary.rb
- test/models/test_ranking.rb
* Remove comments
* Bug fix of Ranking
> Refactoring

- config.ru
- config/database.yml.erb
- lib/app.rb
- lib/batch/write_back_values_and_rankings.rb
- lib/database.rb
- lib/helper/web_utils.rb
- lib/models/gems.rb
- lib/models/ranking.rb
- lib/models/statistics.rb
- lib/models/trend.rb
- lib/models/trend_data.rb
- lib/models/trend_data_set.rb
- test/batch/test_update_daily_summary.rb
- test/models/test_ranking.rb
> BestGemsAPI v2 for transport data to new server

- Gemfile
- Gemfile.lock
- tools/bestgems_api.rb
- tools/export_all_data_to_csv.rb
- tools/transport_all_data.rb
```bash
bundle exec ruby tools/transport_all_data.rb http://source.bestgems.org/api http://destination.bestgems.org/api bestgems > transport_all_data.log
```
```bash
bundle exec ruby lib/batch/update_master.rb
bundle exec ruby lib/batch/write_back_values_and_rankings.rb
bundle exec ruby lib/batch/update_featured_score.rb
bundle exec ruby lib/batch/update_featured_ranking.rb
```
> Add transport_all_data.rb tool

- lib/app.rb
- lib/models/gem_version.rb
- lib/models/gems.rb
- views/gems.erb
* Display number of versions trends.
* Display popular versions.
> Display versions

- bin/batch.sh
- lib/batch/delete_old_data.rb
* Delete unnecessary data from RDB everyday to prevent RDB bulking.
* Since time series data is referenced from Level DB, deleting RDB data has no disadvantage.
> Delete old data

- lib/models/gems.rb
Fix following error. 
> TypeError: no implicit conversion of Hash into Array
> Fix type error

- lib/app.rb
- lib/models/gems.rb
Fix following error.
> NoMethodError: undefined method `[]' for nil:NilClass
> Fix NoMethodError

- views/gems.erb
> Fix major.minor version

- lib/app.rb
- lib/models/gems.rb
- migrations/018_add_enable_column_to_gems_table.rb
- views/disabled.erb
Hide some gems which are should not be displayed on some screens and sitemap.
> Add enable flag to gems

- views/search.erb
> change `resuts` to `results`

- tools/import_gem_detail.rb
> Fix stop import gem detail

- lib/batch/scraping_all_gems.rb
- test/batch/test_scraping_all_gems.rb
> Fix parsing of number of gems

- lib/batch/scraping_all_gems.rb
> Skip error gems page
